change logic for all guard, rewriting code in affiliates module
OLEKSII-DROZDIUK/partner_CRM pull request #2
Opened 2020-11-13 11:07 UTC by OLEKSII-DROZDIUK

переписал affiliates module
изменил логику гвардов, чтобы ходили в свой сервис, а не к юзеру и вынес  в одну функцию

2020-11-13 14:52 UTC, dimakozachkov requested changes

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/controllers/affiliates.controller.ts
> +      private async getAll(): Promise<AffiliateDto[]> {
В контроллерах методы которые будут вызываться роутером сделай с модификатором доступа public. В силу особеностей js оно не влияет ни на что, но в других языках была бы проблема. Это чисто косметическое решение.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/controllers/affiliates.controller.ts
>      @Get('/all')
По restful тут не должно быть роута **@Get('/all')**, тут должен быть **@Get()**. Т.е. роут для этого метода будет **/affiliates**.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/controllers/affiliates.controller.ts
>      @Post('/create')
По restful тут не должно быть роута **@Post('/create')**, тут должен быть **@Post()**. Т.е. роут для этого метода будет /affiliates с http методом post.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/controllers/affiliates.controller.ts
> +      async create(@Body() body: AffiliateDto): Promise<Affiliates> {
Ты пропустил **@UsePipes(ValidationPipe)**.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/controllers/affiliates.controller.ts
> +    @Put('/update')
Ты пропустил **@UsePipes(ValidationPipe)**.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +			await this.affiliatesRepository
Тут стоит пересмотреть код. Вначале используешь await, а потом у тебя вызывается then

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +      return uiObjAffiliates;
Попробуй как-то вот так:
```
const affiliates: Affiliates[] = await this.affiliatesRepository.find({ relations: ["manager"] });

return affiliates.map(affiliate => (
    {...affitiate, manager: affiliate.manager.name } as AffiliateDto
));
```

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +    public create(affiliate: AffiliateDto) {
Тут вводишь в заблуждение названием переменных. Назови `affiliate: AffiliateDto` как `data: AffiliateDto` или `affiliateDto: AffiliateDto`.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +				newAffiliate.status = status;
Это всё можно заменить вот так:

```
const newAffiliate = new Affiliates();
Object.assing(newAffiliate, affiliate);
```

Или даже вот так:

```
const newAffiliate = this.affiliatesRepository.create(affiliate);
```

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +    public async update(affiliate: AffiliateDto) {
Точно так же как и в create.
#Тут вводишь в заблуждение названием переменных. Назови affiliate: AffiliateDto как data: AffiliateDto или affiliateDto: AffiliateDto.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +					.findOneOrFail({ id });  // if no found its go to catch
Тут можно не ставить `{ id }`, метод `findOneOrFail` может принимать не только объект, но и строку, число и ещё что-то. Т.е. можно написать `await this.affiliatesRepository.findOneOrFail(id);`

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/auth/service/auth.service.ts
>        })
await и then в одном месте. Нужно поправить.

Должно получиться что-то типа такого:
```
const user: User = await this.userRepository.findOne({name});
if (!user) {
    throw new NotFoundException();
}

const isValid = this.comparePassword(password, user.password);
if (!isValid) {
    throw new HttpException('Incorrect password', HttpStatus.FORBIDDEN);
}

return this.generateAccessToken(user.id, user.role);
```

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/auth/service/auth.service.ts
> +  public findUser(context: ExecutionContext): Promise<User> {
Ты в сервис передаёшь контекст выполнения, этого делать не нужно. В сервисе должна быть только бизнес логика, а тут ты делаешь завязку на что-то другое, что не относитя к бизнес логике.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/users/services/users.service.ts
>    public generateHashPassword(pass: string) {
`const salt = Number(process.env.BCRYPT_SALT);` ты должен получать значение не из процесса(`process.env.BCRYPT_SALT`), а из конфига. Т.е. тебе нужно добавить конфиг, который будет получать данные с `process.env.BCRYPT_SALT`, а сервис будет получать эти данные с конфига.

2020-11-13 14:52 UTC, dimakozachkov commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +				throw new HttpException('Server error, can create affiliate', HttpStatus.INTERNAL_SERVER_ERROR);
Опечатка, can замени на can't, а ещё лучше на cannot, это более соответствует. Так как can't не просто сокращение от cannot, а имеет значение "не могу потому что у меня есть отмазка", а cannot "не могу потому что нет возможности".

2020-11-16 07:42 UTC, OLEKSII-DROZDIUK commented on backend/src/modules/affiliates/services/affiliates.service.ts
> +					.findOneOrFail({ id });  // if no found its go to catch
Если это никак не влияет на скорость, я бы оставил так. Мне так более понятно.

2020-11-17 13:26 UTC, dimakozachkov approved these changes

2020-11-17 13:26 UTC, dimakozachkov commented on backend/src/modules/auth/service/auth.service.ts
>      this.userRepository = this.connection.getRepository(User);
Получай репозаторий через иньекцию зависимостей.

2020-11-17 13:32 UTC, merged